### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by phihos** [totaler/sepa#4]
Hi,

I am looking for a sepa xml generator in Python and your project seems to be the only one right now. So thank you very much for your effort :-)

However I can not quite understand how to operate it just by looking at the code. Could you provide a small example in your README?

**Comment by totaler** [comment]
Hello,

This library depends on another one that we use internally and need some little work to publish it. As soon as the other piece of the puzzle is ready, we will add some examples. You will not have to wait a lot of time, i promise.

Thank you for your interest

**Comment by ecarreras** [comment]
We have released the library used to serialize the python objects to XML [LibComXML](https://github.com/gisce/libComXML) we need some effort to make more documentation and examples but now it's available

**Comment by totaler** [comment]
I have added a little use example in the reame file and @ecarreras made the same for https://github.com/gisce/libComXML library a few days ago.

If you have any further questions, please feel free to open a new issue with sepecific questions and i will try to answer.

Thank you for your interest.

**Comment by phihos** [comment]
Thank you very much for the example.

Could you also provide an example on how the typical payments info should look like?

**Comment by j0nes2k** [comment]
+1, I am not sure how payments should look like at the moment.
